#!/bin/bash
cd /home/ubuntu/auth_app
export AUTH_DB_URL=kesavan.db.elephantsql.com/cwbyqxkm
export AUTH_DB_USER=cwbyqxkm
export AUTH_DB_PWD=Ye-IqlkdvaDtaY4hmTIk6UVjowND3WPL
export AUTH_SVC_PORT=:5000
export JWT_SECRET=123455
./auth_app > /dev/null 2> /dev/null < /dev/nul &




