#!/bin/bash
cd /home/ubuntu/auth_app
export AUTH_DB_URL="POSTGRESDB URL"
export AUTH_DB_USER="DB USER"
export AUTH_DB_PWD="DB PWD"
export AUTH_SVC_PORT=:5000
export JWT_SECRET=123455
./auth_app > /dev/null 2> /dev/null < /dev/nul &
