// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: pkg/pb/identity_verification.service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerifyNINRequest is the request message for verifying NIN
type VerifyNINRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdNumber   string `protobuf:"bytes,1,opt,name=idNumber,proto3" json:"idNumber,omitempty"`
	Firstname  string `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname   string `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Middlename string `protobuf:"bytes,4,opt,name=middlename,proto3" json:"middlename,omitempty"`
	Dob        string `protobuf:"bytes,5,opt,name=dob,proto3" json:"dob,omitempty"`
	Phone      string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email      string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Gender     string `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *VerifyNINRequest) Reset() {
	*x = VerifyNINRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyNINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINRequest) ProtoMessage() {}

func (x *VerifyNINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINRequest.ProtoReflect.Descriptor instead.
func (*VerifyNINRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyNINRequest) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *VerifyNINRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *VerifyNINRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *VerifyNINRequest) GetMiddlename() string {
	if x != nil {
		return x.Middlename
	}
	return ""
}

func (x *VerifyNINRequest) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *VerifyNINRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifyNINRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyNINRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

// VerifyNINResponse is the response message for verifying NIN
type VerifyNINResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Applicant *VerifyNINResponse_Applicant `protobuf:"bytes,2,opt,name=applicant,proto3" json:"applicant,omitempty"`
	Summary   *VerifyNINResponse_Summary   `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Status    *VerifyNINResponse_Status    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Nin       *VerifyNINResponse_Nin       `protobuf:"bytes,5,opt,name=nin,proto3" json:"nin,omitempty"`
}

func (x *VerifyNINResponse) Reset() {
	*x = VerifyNINResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyNINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINResponse) ProtoMessage() {}

func (x *VerifyNINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINResponse.ProtoReflect.Descriptor instead.
func (*VerifyNINResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyNINResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VerifyNINResponse) GetApplicant() *VerifyNINResponse_Applicant {
	if x != nil {
		return x.Applicant
	}
	return nil
}

func (x *VerifyNINResponse) GetSummary() *VerifyNINResponse_Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *VerifyNINResponse) GetStatus() *VerifyNINResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VerifyNINResponse) GetNin() *VerifyNINResponse_Nin {
	if x != nil {
		return x.Nin
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId  string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SecretKey string `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoginRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyNINResponse_Applicant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
}

func (x *VerifyNINResponse_Applicant) Reset() {
	*x = VerifyNINResponse_Applicant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyNINResponse_Applicant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINResponse_Applicant) ProtoMessage() {}

func (x *VerifyNINResponse_Applicant) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINResponse_Applicant.ProtoReflect.Descriptor instead.
func (*VerifyNINResponse_Applicant) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *VerifyNINResponse_Applicant) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *VerifyNINResponse_Applicant) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

type VerifyNINResponse_Summary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NinCheck *VerifyNINResponse_Summary_NinCheck `protobuf:"bytes,1,opt,name=nin_check,json=ninCheck,proto3" json:"nin_check,omitempty"`
}

func (x *VerifyNINResponse_Summary) Reset() {
	*x = VerifyNINResponse_Summary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyNINResponse_Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINResponse_Summary) ProtoMessage() {}

func (x *VerifyNINResponse_Summary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINResponse_Summary.ProtoReflect.Descriptor instead.
func (*VerifyNINResponse_Summary) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *VerifyNINResponse_Summary) GetNinCheck() *VerifyNINResponse_Summary_NinCheck {
	if x != nil {
		return x.NinCheck
	}
	return nil
}

type VerifyNINResponse_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State  string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *VerifyNINResponse_Status) Reset() {
	*x = VerifyNINResponse_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyNINResponse_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINResponse_Status) ProtoMessage() {}

func (x *VerifyNINResponse_Status) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINResponse_Status.ProtoReflect.Descriptor instead.
func (*VerifyNINResponse_Status) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{1, 2}
}

func (x *VerifyNINResponse_Status) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *VerifyNINResponse_Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VerifyNINResponse_Nin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nin        string `protobuf:"bytes,1,opt,name=nin,proto3" json:"nin,omitempty"`
	Firstname  string `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname   string `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Middlename string `protobuf:"bytes,4,opt,name=middlename,proto3" json:"middlename,omitempty"`
	Phone      string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender     string `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthdate  string `protobuf:"bytes,7,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Photo      string `protobuf:"bytes,8,opt,name=photo,proto3" json:"photo,omitempty"`
	Address    string `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *VerifyNINResponse_Nin) Reset() {
	*x = VerifyNINResponse_Nin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyNINResponse_Nin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINResponse_Nin) ProtoMessage() {}

func (x *VerifyNINResponse_Nin) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINResponse_Nin.ProtoReflect.Descriptor instead.
func (*VerifyNINResponse_Nin) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{1, 3}
}

func (x *VerifyNINResponse_Nin) GetNin() string {
	if x != nil {
		return x.Nin
	}
	return ""
}

func (x *VerifyNINResponse_Nin) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *VerifyNINResponse_Nin) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *VerifyNINResponse_Nin) GetMiddlename() string {
	if x != nil {
		return x.Middlename
	}
	return ""
}

func (x *VerifyNINResponse_Nin) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifyNINResponse_Nin) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *VerifyNINResponse_Nin) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *VerifyNINResponse_Nin) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *VerifyNINResponse_Nin) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyNINResponse_Summary_NinCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       string                                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	FieldMatches *VerifyNINResponse_Summary_NinCheck_FieldMatches `protobuf:"bytes,2,opt,name=fieldMatches,proto3" json:"fieldMatches,omitempty"`
}

func (x *VerifyNINResponse_Summary_NinCheck) Reset() {
	*x = VerifyNINResponse_Summary_NinCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyNINResponse_Summary_NinCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINResponse_Summary_NinCheck) ProtoMessage() {}

func (x *VerifyNINResponse_Summary_NinCheck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINResponse_Summary_NinCheck.ProtoReflect.Descriptor instead.
func (*VerifyNINResponse_Summary_NinCheck) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *VerifyNINResponse_Summary_NinCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VerifyNINResponse_Summary_NinCheck) GetFieldMatches() *VerifyNINResponse_Summary_NinCheck_FieldMatches {
	if x != nil {
		return x.FieldMatches
	}
	return nil
}

type VerifyNINResponse_Summary_NinCheck_FieldMatches struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname bool `protobuf:"varint,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname  bool `protobuf:"varint,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
}

func (x *VerifyNINResponse_Summary_NinCheck_FieldMatches) Reset() {
	*x = VerifyNINResponse_Summary_NinCheck_FieldMatches{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyNINResponse_Summary_NinCheck_FieldMatches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINResponse_Summary_NinCheck_FieldMatches) ProtoMessage() {}

func (x *VerifyNINResponse_Summary_NinCheck_FieldMatches) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_identity_verification_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINResponse_Summary_NinCheck_FieldMatches.ProtoReflect.Descriptor instead.
func (*VerifyNINResponse_Summary_NinCheck_FieldMatches) Descriptor() ([]byte, []int) {
	return file_pkg_pb_identity_verification_service_proto_rawDescGZIP(), []int{1, 1, 0, 0}
}

func (x *VerifyNINResponse_Summary_NinCheck_FieldMatches) GetFirstname() bool {
	if x != nil {
		return x.Firstname
	}
	return false
}

func (x *VerifyNINResponse_Summary_NinCheck_FieldMatches) GetLastname() bool {
	if x != nil {
		return x.Lastname
	}
	return false
}

var File_pkg_pb_identity_verification_service_proto protoreflect.FileDescriptor

var file_pkg_pb_identity_verification_service_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xde, 0x01, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49,
	0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x6f, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x62,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x22, 0xf8, 0x07, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e,
	0x49, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x50, 0x0a, 0x09, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e,
	0x74, 0x52, 0x09, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x12, 0x4a, 0x0a, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x47, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x3e, 0x0a, 0x03, 0x6e, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x69, 0x6e, 0x52, 0x03, 0x6e, 0x69,
	0x6e, 0x1a, 0x45, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0xbc, 0x02, 0x0a, 0x07, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x12, 0x56, 0x0a, 0x09, 0x6e, 0x69, 0x6e, 0x5f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x4e, 0x69, 0x6e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x08, 0x6e, 0x69, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x1a, 0xd8, 0x01, 0x0a,
	0x08, 0x4e, 0x69, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x6a, 0x0a, 0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x4e, 0x69, 0x6e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52,
	0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x1a, 0x48, 0x0a,
	0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a,
	0xed, 0x01, 0x0a, 0x03, 0x4e, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x4a, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x25, 0x0a, 0x0d, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x32, 0xaa, 0x02, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x09, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e, 0x12, 0x27, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e,
	0x49, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0a, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x56, 0x4e, 0x49, 0x4e, 0x12, 0x27, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4e, 0x49, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x4e, 0x49, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x08, 0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_pb_identity_verification_service_proto_rawDescOnce sync.Once
	file_pkg_pb_identity_verification_service_proto_rawDescData = file_pkg_pb_identity_verification_service_proto_rawDesc
)

func file_pkg_pb_identity_verification_service_proto_rawDescGZIP() []byte {
	file_pkg_pb_identity_verification_service_proto_rawDescOnce.Do(func() {
		file_pkg_pb_identity_verification_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_identity_verification_service_proto_rawDescData)
	})
	return file_pkg_pb_identity_verification_service_proto_rawDescData
}

var file_pkg_pb_identity_verification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_pb_identity_verification_service_proto_goTypes = []interface{}{
	(*VerifyNINRequest)(nil),                                // 0: identity_verification.VerifyNINRequest
	(*VerifyNINResponse)(nil),                               // 1: identity_verification.VerifyNINResponse
	(*LoginRequest)(nil),                                    // 2: identity_verification.LoginRequest
	(*LoginResponse)(nil),                                   // 3: identity_verification.LoginResponse
	(*VerifyNINResponse_Applicant)(nil),                     // 4: identity_verification.VerifyNINResponse.Applicant
	(*VerifyNINResponse_Summary)(nil),                       // 5: identity_verification.VerifyNINResponse.Summary
	(*VerifyNINResponse_Status)(nil),                        // 6: identity_verification.VerifyNINResponse.Status
	(*VerifyNINResponse_Nin)(nil),                           // 7: identity_verification.VerifyNINResponse.Nin
	(*VerifyNINResponse_Summary_NinCheck)(nil),              // 8: identity_verification.VerifyNINResponse.Summary.NinCheck
	(*VerifyNINResponse_Summary_NinCheck_FieldMatches)(nil), // 9: identity_verification.VerifyNINResponse.Summary.NinCheck.FieldMatches
}
var file_pkg_pb_identity_verification_service_proto_depIdxs = []int32{
	4, // 0: identity_verification.VerifyNINResponse.applicant:type_name -> identity_verification.VerifyNINResponse.Applicant
	5, // 1: identity_verification.VerifyNINResponse.summary:type_name -> identity_verification.VerifyNINResponse.Summary
	6, // 2: identity_verification.VerifyNINResponse.status:type_name -> identity_verification.VerifyNINResponse.Status
	7, // 3: identity_verification.VerifyNINResponse.nin:type_name -> identity_verification.VerifyNINResponse.Nin
	8, // 4: identity_verification.VerifyNINResponse.Summary.nin_check:type_name -> identity_verification.VerifyNINResponse.Summary.NinCheck
	9, // 5: identity_verification.VerifyNINResponse.Summary.NinCheck.fieldMatches:type_name -> identity_verification.VerifyNINResponse.Summary.NinCheck.FieldMatches
	0, // 6: identity_verification.VerificationService.VerifyNIN:input_type -> identity_verification.VerifyNINRequest
	0, // 7: identity_verification.VerificationService.VerifyVNIN:input_type -> identity_verification.VerifyNINRequest
	2, // 8: identity_verification.VerificationService.Login:input_type -> identity_verification.LoginRequest
	1, // 9: identity_verification.VerificationService.VerifyNIN:output_type -> identity_verification.VerifyNINResponse
	1, // 10: identity_verification.VerificationService.VerifyVNIN:output_type -> identity_verification.VerifyNINResponse
	3, // 11: identity_verification.VerificationService.Login:output_type -> identity_verification.LoginResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_pb_identity_verification_service_proto_init() }
func file_pkg_pb_identity_verification_service_proto_init() {
	if File_pkg_pb_identity_verification_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_identity_verification_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyNINRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyNINResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyNINResponse_Applicant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyNINResponse_Summary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyNINResponse_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyNINResponse_Nin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyNINResponse_Summary_NinCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_identity_verification_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyNINResponse_Summary_NinCheck_FieldMatches); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_identity_verification_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_identity_verification_service_proto_goTypes,
		DependencyIndexes: file_pkg_pb_identity_verification_service_proto_depIdxs,
		MessageInfos:      file_pkg_pb_identity_verification_service_proto_msgTypes,
	}.Build()
	File_pkg_pb_identity_verification_service_proto = out.File
	file_pkg_pb_identity_verification_service_proto_rawDesc = nil
	file_pkg_pb_identity_verification_service_proto_goTypes = nil
	file_pkg_pb_identity_verification_service_proto_depIdxs = nil
}
